AWSTemplateFormatVersion: 2010-09-09
Description: |
  Contains the infrastructure needed to support the lambda for Dwolla's technical problem
  
Resources:
  
  DwollaLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: .
      Description: Returns the current time as JSON
      Handler: index.handler
      Role: !GetAtt DwollaLambdaRole.Arn
      Runtime: nodejs16.x
      Tags:
        Key: dwolla
        Value: true

  DwollaLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: The execution role for the Dwolla lambda